-- ==============================================================================
-- HOTEL LISTING CRUD APP - SUPABASE DATABASE SCHEMA & POLICIES
-- Run this script in your Supabase Project's SQL Editor (Dashboard -> SQL Editor)
-- ==============================================================================

-- 1. Create the 'hotels' table
CREATE TABLE IF NOT EXISTS public.hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for searching and sorting
CREATE INDEX IF NOT EXISTS idx_hotels_title ON public.hotels (title);
CREATE INDEX IF NOT EXISTS idx_hotels_price ON public.hotels (price);
CREATE INDEX IF NOT EXISTS idx_hotels_created_at ON public.hotels (created_at DESC);

-- ------------------------------------------------------------------------------
-- 2. ROW LEVEL SECURITY (RLS)
-- ------------------------------------------------------------------------------
ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;

-- Policy 1: Anyone (including anonymous users) can view/read hotel listings
CREATE POLICY "Allow public read access on hotels"
    ON public.hotels
    FOR SELECT
    TO anon, authenticated
    USING (true);

-- Policy 2: Anyone can insert new hotel records
-- > NOTE: This is a TEMPORARY OPEN POLICY for development/testing without user auth.
-- > Replace with authenticated checks (e.g. TO authenticated WITH CHECK (auth.uid() IS NOT NULL)) in production!
CREATE POLICY "Allow anon insert (TEMPORARY OPEN POLICY)"
    ON public.hotels
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- Policy 3: Anyone can update existing hotel records
-- > NOTE: This is a TEMPORARY OPEN POLICY for development/testing without user auth.
CREATE POLICY "Allow anon update (TEMPORARY OPEN POLICY)"
    ON public.hotels
    FOR UPDATE
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Policy 4: Anyone can delete hotel records
-- > NOTE: This is a TEMPORARY OPEN POLICY for development/testing without user auth.
CREATE POLICY "Allow anon delete (TEMPORARY OPEN POLICY)"
    ON public.hotels
    FOR DELETE
    TO anon, authenticated
    USING (true);

-- ------------------------------------------------------------------------------
-- 3. SUPABASE STORAGE BUCKET: hotel-images
-- ------------------------------------------------------------------------------
-- Create the public bucket 'hotel-images' if it doesn't already exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('hotel-images', 'hotel-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policy: Allow public access to view images
CREATE POLICY "Public Read on hotel-images"
    ON storage.objects FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'hotel-images');

-- Storage Policy: Allow public upload of images
-- > NOTE: This is a TEMPORARY OPEN POLICY for demo/development.
CREATE POLICY "Public Upload on hotel-images (TEMPORARY OPEN POLICY)"
    ON storage.objects FOR INSERT
    TO anon, authenticated
    WITH CHECK (bucket_id = 'hotel-images');

-- Storage Policy: Allow updates/deletes of hotel images
CREATE POLICY "Public Delete on hotel-images (TEMPORARY OPEN POLICY)"
    ON storage.objects FOR DELETE
    TO anon, authenticated
    USING (bucket_id = 'hotel-images');
