
CREATE TABLE IF NOT EXISTS public.hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hotels_title ON public.hotels (title);
CREATE INDEX IF NOT EXISTS idx_hotels_price ON public.hotels (price);
CREATE INDEX IF NOT EXISTS idx_hotels_created_at ON public.hotels (created_at DESC);

ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Allow public read access on hotels"
    ON public.hotels
    FOR SELECT
    TO anon, authenticated
    USING (true);
CREATE POLICY "Allow anon insert (TEMPORARY OPEN POLICY)"
    ON public.hotels
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

CREATE POLICY "Allow anon update (TEMPORARY OPEN POLICY)"
    ON public.hotels
    FOR UPDATE
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);


CREATE POLICY "Allow anon delete (TEMPORARY OPEN POLICY)"
    ON public.hotels
    FOR DELETE
    TO anon, authenticated
    USING (true);

INSERT INTO storage.buckets (id, name, public)
VALUES ('hotel-images', 'hotel-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;
CREATE POLICY "Public Read on hotel-images"
    ON storage.objects FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'hotel-images');

CREATE POLICY "Public Upload on hotel-images (TEMPORARY OPEN POLICY)"
    ON storage.objects FOR INSERT
    TO anon, authenticated
    WITH CHECK (bucket_id = 'hotel-images');

CREATE POLICY "Public Delete on hotel-images (TEMPORARY OPEN POLICY)"
    ON storage.objects FOR DELETE
    TO anon, authenticated
    USING (bucket_id = 'hotel-images');
